require 'rspec/core/rake_task'

task :default => %w[spec]

task :spec do
    ruby "lib/tictactoe.rb"
end

desc "run tests for tic tac toe game"

RSpec::Core::RakeTask.new do |task|
    task.rspec_opts = [ '-f documentation', '-r ./rspec_config']
    task.verbose = false
end




